-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.imagekit_temp_uploads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  file_id text NOT NULL UNIQUE,
  file_url text NOT NULL,
  file_name text NOT NULL,
  file_size integer NOT NULL,
  folder text NOT NULL DEFAULT 'temp-pdfs'::text,
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  deleted_at timestamp with time zone,
  note_id uuid,
  user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT imagekit_temp_uploads_pkey PRIMARY KEY (id),
  CONSTRAINT imagekit_temp_uploads_note_id_fkey FOREIGN KEY (note_id) REFERENCES public.notes(id),
  CONSTRAINT imagekit_temp_uploads_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  content text NOT NULL,
  user_id uuid NOT NULL,
  is_public boolean DEFAULT false,
  is_pinned boolean DEFAULT false,
  tags ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  source_type character varying DEFAULT 'manual'::character varying CHECK (source_type::text = ANY (ARRAY['manual'::character varying, 'youtube'::character varying]::text[])),
  source_url text,
  source_metadata jsonb,
  CONSTRAINT notes_pkey PRIMARY KEY (id),
  CONSTRAINT notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.payment_webhooks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_id text NOT NULL,
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  processed boolean DEFAULT false,
  processed_at timestamp with time zone,
  error_message text,
  customer_email text,
  matched_user_id uuid,
  received_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_webhooks_pkey PRIMARY KEY (id),
  CONSTRAINT payment_webhooks_matched_user_id_fkey FOREIGN KEY (matched_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.profile_changes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  field_changed text NOT NULL,
  old_value text,
  new_value text,
  changed_by uuid,
  changed_by_role text,
  changed_at timestamp with time zone DEFAULT now(),
  ip_address text,
  user_agent text,
  CONSTRAINT profile_changes_pkey PRIMARY KEY (id),
  CONSTRAINT profile_changes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT profile_changes_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  tier text NOT NULL CHECK (tier = ANY (ARRAY['free'::text, 'premium'::text, 'advance'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['active'::text, 'expired'::text, 'cancelled'::text, 'pending'::text])),
  payment_method text DEFAULT 'lynk_id'::text,
  payment_id text UNIQUE,
  payment_status text CHECK (payment_status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text, 'cancelled'::text])),
  amount numeric,
  currency text DEFAULT 'IDR'::text,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone NOT NULL,
  customer_email text,
  customer_name text,
  customer_phone text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  auth_user_id uuid UNIQUE,
  username text NOT NULL UNIQUE,
  full_name text NOT NULL,
  phone text,
  role text NOT NULL DEFAULT 'member'::text CHECK (role = ANY (ARRAY['admin'::text, 'panitia'::text, 'ustadz'::text, 'member'::text])),
  subscription_tier text NOT NULL DEFAULT 'free'::text CHECK (subscription_tier = ANY (ARRAY['free'::text, 'premium'::text, 'advance'::text])),
  subscription_status text NOT NULL DEFAULT 'active'::text CHECK (subscription_status = ANY (ARRAY['active'::text, 'expired'::text, 'cancelled'::text])),
  subscription_start_date timestamp with time zone,
  subscription_end_date timestamp with time zone,
  payment_email text,
  avatar_url text,
  bio text,
  auth_type text NOT NULL DEFAULT 'phone'::text,
  is_verified boolean DEFAULT false,
  is_active boolean DEFAULT true,
  force_password_change boolean DEFAULT false,
  password_reset_by_admin boolean DEFAULT false,
  password_reset_at timestamp with time zone,
  password_changed_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_login_at timestamp with time zone,
  telegram_chat_id text UNIQUE,
  telegram_verified_at timestamp without time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT users_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);